// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/7/2024, 8:45:25 PM
const configMerger = require("/Users/colin/development/cofficinado/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.28.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/colin/development/cofficinado/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/plugins/**/*.{js,ts,mjs}","/Users/colin/development/cofficinado/composables/**/*.{js,ts,mjs}","/Users/colin/development/cofficinado/utils/**/*.{js,ts,mjs}","/Users/colin/development/cofficinado/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/colin/development/cofficinado/app.config.{js,ts,mjs}"] } }));

module.exports = config
